from __future__ import annotations

from copy import deepcopy
from typing import Any


EXECUTIVE_DESIGN: dict[str, Any] = {
    "personas": {
        "ceo": {
            "health": {"score": 78, "headline": "Broadly on track — margin needs attention.", "body": "Revenue is ahead of plan, but margin is leaking to FX and API cost ahead of Thursday's board.", "scoreNote": "plan health"},
            "assistant": "Hermes",
            "assistantRole": "chief of staff",
            "brief": "Thursday board readiness is broadly on track, but the board narrative still needs a clean call on margin, FX hedge coverage, and the business units dragging plan.",
            "quote": "Revenue is carrying the story; the real call is whether we close the hedge and stay ahead of the drag.",
            "by": "Hermes · Group CEO chief of staff",
            "threads": [{"key": "briefing", "title": "Thursday board readiness", "preview": "Am I on track for the board on Thursday?"}, {"key": "risk", "title": "Single biggest risk", "preview": "What is the single biggest risk to plan?"}, {"key": "recognition", "title": "Recognition note", "preview": "Who deserves recognition this week?"}],
            "prompts": ["Am I on track for the board on Thursday?", "What is the single biggest risk to plan?", "Who deserves recognition this week?"],
            "drivers": [
                {"key": "digital_health", "label": "Digital Health revenue", "pct": 100, "value": "SAR 186M", "sub": "flat by EOY scenario", "vsPlan": "flat vs plan", "story": "Digital Health is flattening into year-end unless adoption picks up; the board needs to decide whether to treat it as a hold or fund a sharper commercial push.", "movers": {"lifting": [{"name": "Virtual chronic care", "delta": "+3% enrolments"}], "dragging": [{"name": "Enterprise EHR deals", "delta": "slower conversion"}]}},
                {"key": "epharmacy", "label": "e-Pharmacy growth", "pct": 112, "value": "SAR 214M", "sub": "orders +12% WoW", "vsPlan": "+12% vs plan", "story": "e-Pharmacy is the cleanest growth lever in the pack, but it slows if fulfilment capacity is not pulled forward before the refill curve steepens.", "movers": {"lifting": [{"name": "GLP-1 refill cohort", "delta": "+12% orders WoW"}], "dragging": [{"name": "Eastern hub capacity", "delta": "binding in 2 weeks"}]}},
                {"key": "fx_hedge", "label": "FX / hedge coverage", "pct": 99, "value": "19.2% EBITDA", "sub": "hedge decision pending", "vsPlan": "−20 bps vs plan", "story": "FX and API input cost remain the key margin drag; a 60% EUR hedge is the cleanest board action to stabilise the bridge.", "movers": {"lifting": [{"name": "Manufacturing yield", "delta": "+60 bps"}], "dragging": [{"name": "FX exposure", "delta": "~SAR 9k / wk drag"}]}},
                {"key": "healthcare", "label": "Healthcare occupancy", "pct": 96, "value": "81% occupancy", "sub": "below target", "vsPlan": "−3.8% vs plan", "story": "Healthcare occupancy is the only major operating drag in the CEO view; recovery depends on clearing staffing gaps before the variance turns structural.", "movers": {"lifting": [{"name": "Locum cover", "delta": "next week"}], "dragging": [{"name": "Cardiology occupancy", "delta": "below plan"}]}}
            ],
            "findings": [{"title": "SAR 8.6M is recoverable across the group", "tag": "Cross-BU finding", "detail": "Reviewer evidence packets show SAR 8.6M in recoverable value across Tamween, duplicate-vendor spend, and aged AR.", "tone": "down"}, {"title": "FX is building a margin drag", "tag": "Group KPI · EBITDA margin", "detail": "A 60% EUR hedge neutralises most of the current weekly drag.", "tone": "flat"}, {"title": "Cold-chain resilience remains strong", "tag": "Group KPI · Resilience", "detail": "Operational resilience gives the board room confidence while the commercial issues are handled.", "tone": "up"}],
            "developments": [{"title": "NUPCO awards confirmed", "meta": "Capital · today", "impact": "Improves revenue quality and cash timing.", "kind": "win"}, {"title": "Tamween audit confirmed", "meta": "Distribution · yesterday", "impact": "Adds SAR 1.2M into the SAR 8.6M recovery pool.", "kind": "watch"}],
            "week": [{"key": "board", "day": "Thu", "title": "Board meeting", "when": "in 3 days", "prep": "Close the hedge and JV story.", "urgent": True, "prompt": "Am I on track for the board on Thursday?"}, {"key": "jv", "day": "Wed", "title": "GLP-1 JV sign-off", "when": "in 2 days", "prep": "Cash headroom is ready.", "urgent": True, "prompt": "What is the single biggest risk to plan?"}, {"key": "recognition", "day": "Tue", "title": "Weekly note", "when": "tomorrow", "prep": "Carry one clean recognition item upward.", "urgent": False, "prompt": "Who deserves recognition this week?"}],
        },
        "cfo": {
            "health": {"score": 74, "headline": "Liquidity strong — margin quality is the watch.", "body": "Cash is above floor, but FX and API cost still blur the EBITDA bridge.", "scoreNote": "plan health"},
            "assistant": "Atlas",
            "assistantRole": "finance chief of staff",
            "brief": "Liquidity is strong, but margin quality and the EBITDA bridge still need discipline before the board room feels effortless.",
            "quote": "Cash stays above the floor; the board question is hedge quality, not funding survival.",
            "by": "Atlas · Group CFO chief of staff",
            "threads": [{"key": "bridge", "title": "EBITDA bridge", "preview": "Walk me through the EBITDA bridge."}, {"key": "recoverable", "title": "Recovery scan", "preview": "Where is the SAR 8.6M?"}, {"key": "cash", "title": "JV funding", "preview": "Can the JV be funded from cash?"}],
            "prompts": ["Walk me through the EBITDA bridge.", "Where is the SAR 8.6M?", "Can the JV be funded from cash?"],
            "drivers": [{"key": "bridge", "label": "EBITDA bridge", "pct": 99, "value": "19.2%", "sub": "vs 19.4% plan", "vsPlan": "−20 bps vs plan", "story": "Volume and price add; FX and API cost subtract. A 60% EUR hedge recovers most of the visible drag.", "movers": {"lifting": [{"name": "Volume", "delta": "+40 bps"}], "dragging": [{"name": "FX hedge gap", "delta": "−35 bps"}]}}, {"key": "cash", "label": "Liquidity & covenant", "pct": 123, "value": "SAR 1.48B", "sub": "cash vs floor", "vsPlan": "+SAR 280M above floor", "story": "Cash and covenant headroom support the JV funding case.", "movers": {"lifting": [{"name": "Collections", "delta": "+SAR 145M"}], "dragging": [{"name": "JV pre-funding", "delta": "SAR 60M"}]}}, {"key": "wc", "label": "Working capital", "pct": 96, "value": "58 days", "sub": "cash conversion cycle", "vsPlan": "+3 days vs plan", "story": "The cycle is long mainly because inventory is being built early.", "movers": {"lifting": [{"name": "DPO discipline", "delta": "+4 days"}], "dragging": [{"name": "Inventory build", "delta": "+6 days"}]}}, {"key": "quality", "label": "Revenue quality", "pct": 101, "value": "94% recurring", "sub": "mix quality", "vsPlan": "+2.3% vs plan", "story": "Revenue quality stays sound while hedge closure protects conversion to EBITDA.", "movers": {"lifting": [{"name": "NUPCO contracts", "delta": "+SAR 145M annual"}], "dragging": [{"name": "Healthcare one-offs", "delta": "lower elective mix"}]}}],
            "cashPulse": {"title": "Cash Pulse", "note": "four pillars", "pillars": [{"label": "Cash in", "value": "SAR 612M", "sub": "collections", "delta": "+SAR 145M NUPCO", "tone": "up"}, {"label": "Cash out", "value": "SAR 534M", "sub": "disbursed", "delta": "DPO +4 days", "tone": "flat"}, {"label": "At bank", "value": "SAR 1.48B", "sub": "available liquidity", "delta": "+SAR 60M wk", "tone": "up"}, {"label": "Lost / leaking", "value": "SAR 8.6M", "sub": "recoverable group-wide", "delta": "invoke leakage scan", "tone": "down"}]},
            "findings": [{"title": "FX drag remains visible", "tag": "Bridge", "detail": "60% EUR hedge decision pending.", "tone": "flat"}, {"title": "SAR 8.6M is recoverable", "tag": "Cash-Leakage add-on", "detail": "Evidence packets are ready for review.", "tone": "down"}, {"title": "Covenant headroom remains comfortable", "tag": "Liquidity", "detail": "1.6x leverage against a 2.6x covenant.", "tone": "up"}],
            "developments": [{"title": "Rates eased", "meta": "Treasury · today", "impact": "Supports the cash-funding case.", "kind": "win"}],
            "week": [{"key": "board", "day": "Thu", "title": "Board meeting", "when": "in 3 days", "prep": "Own the margin and hedge story.", "urgent": True, "prompt": "Walk me through the EBITDA bridge."}, {"key": "jv", "day": "Wed", "title": "JV funding", "when": "in 2 days", "prep": "Confirm fund-from-cash option.", "urgent": True, "prompt": "Can the JV be funded from cash?"}, {"key": "review", "day": "Tue", "title": "Recovery review", "when": "tomorrow", "prep": "Carry the SAR 8.6M evidence set.", "urgent": False, "prompt": "Where is the SAR 8.6M?"}],
        },
        "gm": {
            "health": {"score": 84, "headline": "Strong week — capacity is the constraint.", "body": "Demand is healthy; capacity and SLA discipline decide whether the week stays beautiful or breaks.", "scoreNote": "plan health"},
            "assistant": "Iris",
            "assistantRole": "ground operator",
            "brief": "The growth line is strong; the operating question is whether capacity can keep up without sacrificing service quality.",
            "quote": "Demand is healthy — capacity and service discipline decide the week.",
            "by": "Iris · BU GM chief of staff",
            "threads": [{"key": "hub", "title": "Eastern hub bottleneck", "preview": "How long until the Eastern hub caps us?"}, {"key": "capacity", "title": "Capacity bind", "preview": "Where is capacity binding first?"}, {"key": "ceo", "title": "Opportunity call", "preview": "What do I owe the CEO before tomorrow's call?"}],
            "prompts": ["How long until the Eastern hub caps us?", "Where is capacity binding first?", "What do I owe the CEO before tomorrow's call?"],
            "drivers": [{"key": "revenue", "label": "Unit revenue", "pct": 112, "value": "SAR 214M", "sub": "quarter to date", "vsPlan": "+12% vs plan", "story": "Revenue is compounding on the refill cohort, but capacity binds first in the Eastern hub.", "movers": {"lifting": [{"name": "Riyadh region", "delta": "+18% orders"}], "dragging": [{"name": "Eastern region", "delta": "capacity-capped"}]}}, {"key": "capacity", "label": "Capacity posture", "pct": 94, "value": "94% utilisation", "sub": "Eastern hub", "vsPlan": "binding soon", "story": "Capacity is the first operational ceiling and determines whether service holds through peak.", "movers": {"lifting": [{"name": "Automation line", "delta": "ready to pull forward"}], "dragging": [{"name": "Eastern hub", "delta": "binds in 2 weeks"}]}}, {"key": "sla", "label": "Fulfilment SLA", "pct": 100, "value": "96.5% on-time", "sub": "2.0 days", "vsPlan": "on plan", "story": "SLA and fulfilment quality are holding, but they will slip if the hub bind is ignored.", "movers": {"lifting": [{"name": "Route density", "delta": "stable"}], "dragging": [{"name": "Eastern surge", "delta": "service risk"}]}}, {"key": "cost", "label": "Cost to serve", "pct": 98, "value": "SAR 38/order", "sub": "below plan", "vsPlan": "−2% vs plan", "story": "Cost to serve remains disciplined while the capacity issue is managed.", "movers": {"lifting": [{"name": "Warehouse automation", "delta": "lower touch time"}], "dragging": [{"name": "Surge routing", "delta": "+8% in East"}]}}],
            "findings": [{"title": "Refill cohort is compounding", "tag": "Revenue", "detail": "+12% WoW and capacity is the only ceiling.", "tone": "up"}, {"title": "Eastern region capacity binds within 2 weeks", "tag": "Fulfilment", "detail": "Shift volume or pull forward automation.", "tone": "flat"}],
            "developments": [{"title": "App conversion hit a new high", "meta": "Digital · today", "impact": "Supports the revenue beat.", "kind": "win"}],
            "week": [{"key": "ceo", "day": "Tue", "title": "Opportunity call with the CEO", "when": "tomorrow", "prep": "Bring the 12% WoW curve and the Eastern bottleneck.", "urgent": True, "prompt": "What do I owe the CEO before tomorrow's call?"}, {"key": "capacity", "day": "Wed", "title": "Capacity decision", "when": "in 2 days", "prep": "Pull forward the automation line if needed.", "urgent": True, "prompt": "Where is capacity binding first?"}, {"key": "hub", "day": "Fri", "title": "Hub readiness", "when": "in 4 days", "prep": "Confirm how long until the Eastern hub caps out.", "urgent": False, "prompt": "How long until the Eastern hub caps us?"}],
        },
        "bucfo": {
            "health": {"score": 66, "headline": "Margin recovering — leakage and cutover in flight.", "body": "Revenue is flat to plan while the SAR 1.2M leakage and S/4HANA cutover still need exact control.", "scoreNote": "plan health"},
            "assistant": "Argus",
            "assistantRole": "exacting controller",
            "brief": "Tamween's story is about exact control: leakage, DSO, and cutover recovery.",
            "quote": "The number improves only when the recovery sequence is real and the commentary rides up with it.",
            "by": "Argus · BU CFO chief of staff",
            "threads": [{"key": "variance", "title": "Variance note", "preview": "Draft my variance note on the margin drag."}, {"key": "recovery", "title": "Recovery path", "preview": "What is the SAR 1.2M recovery path?"}, {"key": "cutover", "title": "Cutover close", "preview": "What still needs closing before the cost line steps down?"}],
            "prompts": ["Draft my variance note on the margin drag.", "What is the SAR 1.2M recovery path?", "What still needs closing before the cost line steps down?"],
            "drivers": [{"key": "margin", "label": "Margin drag", "pct": 94, "value": "8.9%", "sub": "below plan", "vsPlan": "−60 bps vs plan", "story": "Margin is recovering, but leakage and dual-running cost still compress the line.", "movers": {"lifting": [{"name": "Freight renegotiation", "delta": "+20 bps"}], "dragging": [{"name": "Leakage", "delta": "SAR 1.2M"}]}}, {"key": "recovery", "label": "Recovery path", "pct": 88, "value": "SAR 1.2M", "sub": "audit-confirmed", "vsPlan": "in progress", "story": "The SAR 1.2M recovery path is sequenced across institutional AR and duplicate-vendor lines.", "movers": {"lifting": [{"name": "Collections plan", "delta": "drafted"}], "dragging": [{"name": "Aged AR", "delta": ">90 days"}]}}, {"key": "cutover", "label": "Cutover close", "pct": 92, "value": "+30 bps cost", "sub": "dual running", "vsPlan": "temporary", "story": "S/4HANA cutover still carries temporary dual-running cost until the legacy retirement date is locked.", "movers": {"lifting": [{"name": "UAT passed", "delta": "ready for go-live"}], "dragging": [{"name": "Legacy overlap", "delta": "+30 bps"}]}}, {"key": "dso", "label": "Collections discipline", "pct": 95, "value": "91 days", "sub": "institutional account watch", "vsPlan": "+5 days vs plan", "story": "Collections discipline remains the cleanest way to accelerate the margin recovery commentary.", "movers": {"lifting": [{"name": "Payment-plan options", "delta": "prepared"}], "dragging": [{"name": "Institutional A", "delta": "past 90 days"}]}}],
            "findings": [{"title": "SAR 1.2M leakage confirmed by audit", "tag": "Margin", "detail": "Recovery sequence is drafted.", "tone": "down"}, {"title": "Cutover dual-running adds cost", "tag": "Operating cost", "detail": "Temporary while legacy remains active.", "tone": "flat"}],
            "developments": [{"title": "S/4HANA cutover passed UAT", "meta": "Transformation · yesterday", "impact": "Cost relief comes after legacy retirement.", "kind": "win"}],
            "week": [{"key": "note", "day": "Mon", "title": "Variance note to Group CFO", "when": "due today", "prep": "Confirm the SAR 1.2M recovery path.", "urgent": True, "prompt": "Draft my variance note on the margin drag."}, {"key": "collections", "day": "Tue", "title": "Collections call", "when": "tomorrow", "prep": "Bring aged-AR payment-plan options.", "urgent": True, "prompt": "What is the SAR 1.2M recovery path?"}, {"key": "cutover", "day": "Thu", "title": "Cutover go-live review", "when": "in 3 days", "prep": "Lock the legacy retirement date.", "urgent": False, "prompt": "What still needs closing before the cost line steps down?"}],
        },
        "logistics": {
            "health": {"score": 80, "headline": "Resilience is carrying confidence.", "body": "Cold-chain reliability is the quiet strength in the packet.", "scoreNote": "resilience"},
            "assistant": "Vega",
            "assistantRole": "logistics chief of staff",
            "brief": "Cold-chain and service reliability remain the calm strength in the packet.",
            "quote": "Cold-chain credibility lets the board focus on strategy instead of firefighting.",
            "by": "Vega · logistics chief of staff",
            "threads": [{"key": "service", "title": "Cold-chain watch", "preview": "What keeps service credibility strongest this week?"}, {"key": "continuity", "title": "Continuity risk", "preview": "Where could continuity slip before the board?"}, {"key": "win", "title": "Operational win", "preview": "Which logistics win should the board hear?"}],
            "prompts": ["What keeps service credibility strongest this week?", "Where could continuity slip before the board?", "Which logistics win should the board hear?"],
            "drivers": [{"key": "service", "label": "Service credibility", "pct": 101, "value": "96.5% on-time", "sub": "continuity and delivery", "vsPlan": "+1 pt vs plan", "story": "Service credibility remains strong because continuity stayed boring and precise.", "movers": {"lifting": [{"name": "Riyadh hub", "delta": "steady flow"}], "dragging": [{"name": "Eastern surge", "delta": "capacity pressure"}]}}, {"key": "coldchain", "label": "Cold-chain integrity", "pct": 99, "value": "99.4%", "sub": "record week", "vsPlan": "record", "story": "Cold-chain integrity is the logistics proof point the board should hear.", "movers": {"lifting": [{"name": "Summer peak control", "delta": "no excursions"}], "dragging": [{"name": "Eastern alert", "delta": "cleared"}]}}, {"key": "cost", "label": "Cost to serve", "pct": 98, "value": "SAR 38/order", "sub": "within tolerance", "vsPlan": "on plan", "story": "Fuel pressure is visible, but cost discipline has not broken the resilience story.", "movers": {"lifting": [{"name": "Route density", "delta": "−5%"}], "dragging": [{"name": "Fuel", "delta": "+2.6% vs plan"}]}}, {"key": "readiness", "label": "Board readiness", "pct": 101, "value": "room confidence", "sub": "operations story clear", "vsPlan": "board-safe", "story": "Operations should arrive in the room as proof and reassurance, not as a scramble.", "movers": {"lifting": [{"name": "Recognition drafted", "delta": "ready"}], "dragging": [{"name": "Continuity slip risk", "delta": "watch East"}]}}],
            "findings": [{"title": "Cold-chain hit 99.4% — best ever", "tag": "Resilience", "detail": "No excursions in the last 30 days.", "tone": "up"}, {"title": "Eastern region surge remains the one service risk", "tag": "Capacity", "detail": "Extra load needs careful orchestration before it shows in the board packet.", "tone": "flat"}],
            "developments": [{"title": "Recognition drafted for the Logistics GM", "meta": "Hermes + Vega · today", "impact": "Ready to ride upward into the weekly note.", "kind": "win"}],
            "week": [{"key": "continuity", "day": "Tue", "title": "Continuity review", "when": "tomorrow", "prep": "Re-check the Eastern hub and route assumptions.", "urgent": True, "prompt": "Where could continuity slip before the board?"}, {"key": "board", "day": "Thu", "title": "Board note", "when": "in 3 days", "prep": "Carry the cold-chain record into the board narrative.", "urgent": False, "prompt": "Which logistics win should the board hear?"}, {"key": "service", "day": "Fri", "title": "Service review", "when": "in 4 days", "prep": "Keep service credibility explicit.", "urgent": False, "prompt": "What keeps service credibility strongest this week?"}],
        },
    },
    "board": {"assistant": "Minerva", "meeting": {"title": "Q2 Board Meeting", "when": "in 3 days", "date": "Thu 18 Jun · 14:00", "room": "Riyadh HQ + remote"}, "governance": "Nothing reaches the board until the Group CEO approves it.", "kpis": [{"key": "revenue", "label": "Revenue", "pct": 102, "value": "SAR 2.09B", "sub": "quarter to date"}, {"key": "ebitda", "label": "EBITDA margin", "pct": 99, "value": "19.2%", "sub": "vs 19.4% plan"}, {"key": "cash", "label": "Cash vs floor", "pct": 123, "value": "SAR 1.48B", "sub": "vs SAR 1.2B floor"}, {"key": "localisation", "label": "Vision 2030 localisation", "pct": 104, "value": "38.4% Saudization", "sub": "vs 37% target"}], "decks": [{"title": "Group performance & plan health", "by": "Office of the CEO", "status": "approved", "pages": 14, "tag": "group KPI"}, {"title": "Margin & the FX hedge decision", "by": "Group CFO · Atlas", "status": "approved", "pages": 9, "tag": "decision"}, {"title": "GLP-1 JV — supply lock & funding", "by": "e-Pharmacy + Capital", "status": "approved", "pages": 11, "tag": "decision"}, {"title": "Tamween recovery & cutover", "by": "BU CFO · Argus", "status": "pending CEO approval", "pages": 7, "tag": "rolled-up"}], "supplementary": [{"q": "What is the downside if EUR strengthens after a 60% hedge?", "to": "Group CEO", "status": "sent"}, {"q": "Can the JV be funded fully from cash without touching the facility?", "to": "Group CFO", "status": "answered"}], "livePrompts": ["Why is EBITDA 20 bps under plan?", "Show the hedge downside", "Is the JV funded from cash?"], "actions": [{"item": "Ratify the 60% EUR hedge", "owner": "Group CFO", "due": "on approval"}, {"item": "Approve GLP-1 JV signature", "owner": "Group CEO", "due": "this week"}, {"item": "Review Tamween recovery at Q3", "owner": "Audit committee", "due": "Q3"}], "summary": "Board endorsed the margin-protection plan and ratified the hedge; approved the GLP-1 JV subject to final supply terms. Recovery of SAR 8.6M will be reviewed at Q3."},
    "activity": {"line": "5 agents · 25 steps · 15 tool calls — recovered SAR 8.6M of leakage and composed 80% of the board pack", "metrics": [{"k": "agents", "v": "5"}, {"k": "steps", "v": "25"}, {"k": "tool calls", "v": "15"}, {"k": "value found", "v": "SAR 8.6M"}], "log": [{"t": "06:14", "who": "Hermes", "a": "Engaged board-pack composition."}, {"t": "06:05", "who": "Leakage scan", "a": "Recovered SAR 1.2M at Tamween and rolled it into SAR 8.6M group recovery."}]},
    "runningAgents": [{"id": "boardpack", "name": "Board pack composer", "by": "Office of the CEO", "status": "running", "progress": 80, "tag": "board prep", "doing": "Drafting the margin narrative."}, {"id": "leakage", "name": "Leakage recovery scan", "by": "Group CFO", "status": "running", "progress": 38, "tag": "cash · governance", "doing": "Scanning for recoverable spend."}, {"id": "hedge", "name": "FX hedge pre-clearance", "by": "Treasury", "status": "approval", "progress": 100, "tag": "EBITDA", "doing": "A 60% EUR hedge is staged pending approval."}, {"id": "variance", "name": "Variance commentary collector", "by": "Group CFO", "status": "running", "progress": 75, "tag": "rolled-up", "doing": "Gathering BU commentary."}, {"id": "coldchain", "name": "Cold-chain integrity monitor", "by": "Pharma Logistics", "status": "standing", "progress": 91, "tag": "resilience", "doing": "Watching continuity and recognition-ready proof points."}],
    "discoverAgents": [{"id": "covenant", "glyph": "⚖", "name": "Covenant sentinel", "source": "native", "by": "StrategyOS", "desc": "Watches leverage against every covenant.", "connector": "Treasury · loan agreements"}, {"id": "workingcap", "glyph": "◴", "name": "Working-capital optimiser", "source": "native", "by": "StrategyOS", "desc": "Models DSO / DPO / DIO moves.", "connector": "S/4HANA · AR / AP"}, {"id": "scenario", "glyph": "◇", "name": "Scenario planner", "source": "native", "by": "StrategyOS", "desc": "Runs multi-driver what-ifs with no side effects.", "connector": "knowledge graph"}, {"id": "supplier", "glyph": "⬡", "name": "Supplier-risk monitor", "source": "market", "by": "ChainLens", "desc": "Tracks API supplier disruption and lead times.", "connector": "supplier EDI"}],
    "subtools": [{"name": "Spreadsheet", "glyph": "▦", "desc": "Builds and audits models."}, {"name": "Document & PDF", "glyph": "▤", "desc": "Reads decks and contracts."}, {"name": "Calls at scale", "glyph": "☏", "desc": "Runs structured outreach."}, {"name": "Marketing content", "glyph": "✎", "desc": "Drafts recognition notes on-brand."}],
}


def executive_persona_design(persona_id: str) -> dict[str, Any]:
    personas = EXECUTIVE_DESIGN.get("personas") or {}
    return deepcopy(personas.get(persona_id) or personas.get("ceo") or {})


def executive_board_design() -> dict[str, Any]:
    return deepcopy(EXECUTIVE_DESIGN.get("board") or {})


def executive_activity_design() -> dict[str, Any]:
    return deepcopy(EXECUTIVE_DESIGN.get("activity") or {})


def executive_running_agents_design() -> list[dict[str, Any]]:
    return deepcopy(list(EXECUTIVE_DESIGN.get("runningAgents") or []))


def executive_discover_agents_design() -> list[dict[str, Any]]:
    return deepcopy(list(EXECUTIVE_DESIGN.get("discoverAgents") or []))


def executive_subtools_design() -> list[dict[str, Any]]:
    return deepcopy(list(EXECUTIVE_DESIGN.get("subtools") or []))
